### ISSUE TITLE
AssertionError assert not th.isnan(log_prob).any()

### ISSUE THREAD

**Issue by lyh1028** [Shalev-Lifshitz/STEVE-1#13]
I configure the envrionment on wsl  Ubuntu20.04,  my cuda version in nvidia-smi is 11.6
When I run ". run_agent/1_gen_paper_videos.sh" , an assertion error occurs:
( /home/lyh/STEVE-1/steve1/embed_conditioned_policy.py , buttons = pd['buttons'][0, 0, 0, :]  ,the "buttons" contains NaN)
I'm struggling with it, could you give me some assistance? 
The complete error message is as follows：

```
/home/lyh/miniconda3/envs/steve/lib/python3.10/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
[INFO:minedojo.tasks] Loaded 1581 Programmatic tasks, 1560 Creative tasks, and 1 special task: "Playthrough". Totally 3142 tasks loaded.
Loading MineClip...

Generating video for text prompt with name: dig
Loading MineClip...
Loading agent with cond_scale 6.0...
Loading MineRL...
/home/lyh/miniconda3/envs/steve/lib/python3.10/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
Starting new env...
/home/lyh/miniconda3/envs/steve/lib/python3.10/site-packages/numpy/core/numeric.py:330: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(a, fill_value, casting='unsafe')
/home/lyh/miniconda3/envs/steve/lib/python3.10/runpy.py:126: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
  0%|                                                                                                      | 0/3000 [00:00<?, ?it/s]
  0%|                                                                                                      | 0/3000 [00:16<?, ?it/s]
Traceback (most recent call last):
  File "/home/lyh/STEVE-1/steve1/run_agent/run_agent.py", line 100, in <module>
    generate_text_prompt_videos(text_prompt_embeds, args.in_model, args.in_weights, args.text_cond_scale,
  File "/home/lyh/STEVE-1/steve1/run_agent/run_agent.py", line 59, in generate_text_prompt_videos
    run_agent(prompt_embed, gameplay_length, save_video_filepath,
  File "/home/lyh/STEVE-1/steve1/run_agent/run_agent.py", line 37, in run_agent
    minerl_action = agent.get_action(obs, prompt_embed)
  File "/home/lyh/STEVE-1/steve1/MineRLConditionalAgent.py", line 87, in get_action
    agent_action, self.hidden_state, _ = self.policy.act(
  File "/home/lyh/miniconda3/envs/steve/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lyh/STEVE-1/steve1/embed_conditioned_policy.py", line 363, in act
    assert not th.isnan(log_prob).any()
AssertionError
```

**Comment by oriolmirolf** [comment]
Same error here.

**Comment by lyh1028** [comment]
> Same error here.

I reinstall the environment, using pytorch 2.2.2 and downloading weights files with browser. Now it works.

**Comment by oriolmirolf** [comment]
> > Same error here.
> 
> I reinstall the environment, using pytorch 2.2.2 and downloading weights files with browser. Now it works.

I tried and it still not works :(

**Comment by Shalev-Lifshitz** [comment]
Hi there, were you able to get it working? I don't get the same error, unfortunately.
