### ISSUE TITLE
I can't run the run_interactive.py, installed all the requirements inside Ubuntu WSL2 ( Idk what happened)

### ISSUE THREAD

**Issue by tonymacx86PRO** [Shalev-Lifshitz/STEVE-1#8]
(steve) coder@TONY-PC:~/STEVE-1$ python steve1/run_agent/run_interactive.py --in_model data/weights/vpt/2x.model --in_weights data/weights/steve1/steve1.weights --prior_weights data/weights/steve1/steve1_prior.pt --output_video_dirpath data/generated_videos/interactive_videos --cond_scale 6.0
Traceback (most recent call last):
  File "/home/coder/STEVE-1/steve1/run_agent/run_interactive.py", line 9, in <module>
    from steve1.utils.mineclip_agent_env_utils import load_mineclip_agent_env
  File "/home/coder/STEVE-1/steve1/utils/mineclip_agent_env_utils.py", line 6, in <module>
    from steve1.MineRLConditionalAgent import MineRLConditionalAgent
  File "/home/coder/STEVE-1/steve1/MineRLConditionalAgent.py", line 6, in <module>
    from steve1.VPT.agent import MineRLAgent, resize_image, AGENT_RESOLUTION, validate_env, \
  File "/home/coder/STEVE-1/steve1/VPT/agent.py", line 7, in <module>
    from steve1.VPT.lib.action_mapping import CameraHierarchicalMapping
  File "/home/coder/STEVE-1/steve1/VPT/lib/action_mapping.py", line 9, in <module>
    from steve1.VPT.lib.actions import Buttons
  File "/home/coder/STEVE-1/steve1/VPT/lib/actions.py", line 2, in <module>
    import minerl.herobraine.hero.mc as mc
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/__init__.py", line 6, in <module>
    import minerl.herobraine.envs
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/envs.py", line 20, in <module>
    MINERL_TREECHOP_V0 = Treechop()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/treechop_specs.py", line 42, in __init__
    super().__init__(*args,
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 91, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 54, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 38, in __init__
    self.reset()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 44, in reset
    self.actionables = self.create_actionables()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 103, in create_actionables
    return [
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 104, in <listcomp>
    H.KeybasedCommandAction(k, v) for k, v in INVERSE_KEYMAP.items()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/handlers/agent/actions/keyboard.py", line 60, in __init__
    super().__init__(command, spaces.Discrete(len(keys) + 1))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/spaces.py", line 206, in __init__
    self.shape = ()
AttributeError: can't set attribute 'shape'

**Comment by Shalev-Lifshitz** [comment]
Hi there, it seems that you are encountering some error with MineRL. I think this may be because you are running in Windows Subsystem for Linux (when I tried to run MineRL with WSL a while ago, it didn't work well). Can you try running any of the other scripts and seeing if they work? (i.e., `2_gen_vid_for_text_prompt.sh`)

**Comment by tonymacx86PRO** [comment]
I can't know what WSL you used for MineRL (WSL 1 or 2) but I listened that WSL 2 is like a full linux VM, so why it need to have trouble with it? Also I runned the `2_gen_vid_for_text_prompt.sh` and I get the same error (maybe)
```
Traceback (most recent call last):
  File "/home/coder/STEVE-1/steve1/run_agent/run_agent.py", line 11, in <module>
    from steve1.run_agent.paper_prompts import load_text_prompt_embeds, load_visual_prompt_embeds
  File "/home/coder/STEVE-1/steve1/run_agent/paper_prompts.py", line 7, in <module>
    from steve1.utils.mineclip_agent_env_utils import load_mineclip_wconfig
  File "/home/coder/STEVE-1/steve1/utils/mineclip_agent_env_utils.py", line 6, in <module>
    from steve1.MineRLConditionalAgent import MineRLConditionalAgent
  File "/home/coder/STEVE-1/steve1/MineRLConditionalAgent.py", line 6, in <module>
    from steve1.VPT.agent import MineRLAgent, resize_image, AGENT_RESOLUTION, validate_env, \
  File "/home/coder/STEVE-1/steve1/VPT/agent.py", line 7, in <module>
    from steve1.VPT.lib.action_mapping import CameraHierarchicalMapping
  File "/home/coder/STEVE-1/steve1/VPT/lib/action_mapping.py", line 9, in <module>
    from steve1.VPT.lib.actions import Buttons
  File "/home/coder/STEVE-1/steve1/VPT/lib/actions.py", line 2, in <module>
    import minerl.herobraine.hero.mc as mc
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/__init__.py", line 6, in <module>
    import minerl.herobraine.envs
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/envs.py", line 20, in <module>
    MINERL_TREECHOP_V0 = Treechop()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/treechop_specs.py", line 42, in __init__
    super().__init__(*args,
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 91, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 54, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 38, in __init__
    self.reset()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 44, in reset
    self.actionables = self.create_actionables()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 103, in create_actionables
    return [
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 104, in <listcomp>
    H.KeybasedCommandAction(k, v) for k, v in INVERSE_KEYMAP.items()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/handlers/agent/actions/keyboard.py", line 60, in __init__
    super().__init__(command, spaces.Discrete(len(keys) + 1))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/spaces.py", line 206, in __init__
    self.shape = ()
AttributeError: can't set attribute 'shape'
```

**Comment by tonymacx86PRO** [comment]
Also I tried creating the conda env step by step from the README.md but it doesn't work, I have some issues with libraries and I need it to upgrade and etc. I have to many problems but now like I fixed all problems with libraries and now I have problems with the code of MineRL, interesting...

**Comment by tonymacx86PRO** [comment]
Maybe delete the env and reinstall everything? Maybe my python version is not compatible? `Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux`

**Comment by Shalev-Lifshitz** [comment]
The python version looks ok to me, the issue seems to be with MineRL. Do you run into the same error when following the steps in the Hello World tutorial for MineRL? (https://minerl.readthedocs.io/en/latest/tutorials/first_agent.html)

**Comment by tonymacx86PRO** [comment]
Yes! Same error using the hello world example:
Code
```python
import gym
import minerl
import logging
logging.basicConfig(level=logging.DEBUG)

env = gym.make('MineRLBasaltFindCave-v0')

# Note that this command will launch the MineRL environment, which takes time.
# Be patient!
obs = env.reset()

done = False

while not done:
    # Take a random action
    action = env.action_space.sample()
    # In BASALT environments, sending ESC action will end the episode
    # Lets not do that
    action["ESC"] = 0
    obs, reward, done, _ = env.step(action)
    env.render()
```

Output:
```
Traceback (most recent call last):
  File "/home/coder/STEVE-1/hw.py", line 2, in <module>
    import minerl
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/__init__.py", line 6, in <module>
    import minerl.herobraine.envs
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/envs.py", line 20, in <module>
    MINERL_TREECHOP_V0 = Treechop()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/treechop_specs.py", line 42, in __init__
    super().__init__(*args,
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 91, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 54, in __init__
    super().__init__(name, *args, **kwargs)
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 38, in __init__
    self.reset()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_spec.py", line 44, in reset
    self.actionables = self.create_actionables()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 103, in create_actionables
    return [
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/env_specs/human_controls.py", line 104, in <listcomp>
    H.KeybasedCommandAction(k, v) for k, v in INVERSE_KEYMAP.items()
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/handlers/agent/actions/keyboard.py", line 60, in __init__
    super().__init__(command, spaces.Discrete(len(keys) + 1))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minerl/herobraine/hero/spaces.py", line 206, in __init__
    self.shape = ()
AttributeError: can't set attribute 'shape'
```

**Comment by Shalev-Lifshitz** [comment]
I see, in that case I'm not sure how to fix the error as this is something to do with MineRL, not the STEVE-1 code. I would recommend asking the MineRL discord server and posting the Hello World example + error message and letting them know that you are using WSL. I suspect that there is some issue with using MineRL on WSL, but I'm not sure. Here's the link to the discord: https://discord.gg/yzMTERxD

**Comment by Shalev-Lifshitz** [comment]
Sure, I'll just go ahead and close it for now but feel free to open another one if you encounter some other issue!

**Comment by tonymacx86PRO** [comment]
Thanks for some help! I just some junior c# dev and gamer (maybe) so I want to try this project. Thanks for this project, looks good!
